# Generated by Django 2.2.9 on 2021-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211227_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
