# Generated by Django 2.2.9 on 2022-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220208_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
